# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-21 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_text', models.CharField(max_length=100, unique=True)),
                ('add_date', models.DateField(verbose_name='date added')),
            ],
        ),
    ]
